name: Publish site

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  publish-site:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Npm install
        run: |
          npm i
          npm ci

      - name: Build
        run: npm run build

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add CNAME file for gh pages custom domain
        run: echo "www.rotondoillustrazioni.com" > build/CNAME

      - name: Commit and push to gh-pages branch
        run: |
          git --work-tree build add --all
          git commit -m "Automatic Deploy action run by github-actions"
          git push origin HEAD:gh-pages --force
