name: Publish site

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish-site:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy react app to github pages
        uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
